config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/kit-data-manager/base-repo:
      branch: main
      repo: https://github.com/kit-data-manager/base-repo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/kit-data-manager/base-repo git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-amber-snail.sh
        container: qc.acc_snazzy-puce-meerkat
  QC.Doc:
    repos:
      github.com/kit-data-manager/base-repo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-ruby-chipmunk.sh
        container: qc.doc_grumpy-harlequin-cichlid
      github.com/kit-data-manager/base-repo git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-pink-cattle.sh
        container: qc.doc_nippy-chartreuse-chinchilla
      github.com/kit-data-manager/base-repo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-salmon-woodpecker.sh
        container: qc.doc_cloudy-asparagus-dodo
  QC.Lic:
    repos:
      github.com/kit-data-manager/base-repo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-gold-tarantula.sh
        container: qc.lic_wheezy-white-ray
  QC.Sty:
    repos:
      github.com/kit-data-manager/base-repo checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-cornflower-chihuahua.sh
        container: qc.sty_nerdy-burgundy-insect
      github.com/kit-data-manager/base-repo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-violet-bison.sh
        container: qc.sty_boozy-mustard-schnauzer
      github.com/kit-data-manager/base-repo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-chartreuse-fousek.sh
        container: qc.sty_geeky-dandelion-oyster
  QC.Ver:
    repos:
      github.com/kit-data-manager/base-repo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-flax-hare.sh
        container: qc.ver_gloppy-puce-giraffe
timeout: 5400
