config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.7
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/kit-data-manager/base-repo:
      branch: dev
      repo: https://github.com/kit-data-manager/base-repo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/kit-data-manager/base-repo git:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-brass-stingray.sh
        container: qc.acc_chewy-aquamarine-loon
  QC.Doc:
    repos:
      github.com/kit-data-manager/base-repo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-alizarin-yak.sh
        container: qc.doc_nerdy-ruby-ragdoll
      github.com/kit-data-manager/base-repo git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-platinum-oriole.sh
        container: qc.doc_crappy-silver-crane
      github.com/kit-data-manager/base-repo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-purple-cuttlefish.sh
        container: qc.doc_foggy-coral-bombay
  QC.Lic:
    repos:
      github.com/kit-data-manager/base-repo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cardinal-jackal.sh
        container: qc.lic_gummy-razzmatazz-woodlouse
  QC.Met:
    repos:
      github.com/kit-data-manager/base-repo cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-tomato-gibbon.sh
        container: qc.met_thirsty-cinnamon-bobcat
  QC.Sty:
    repos:
      github.com/kit-data-manager/base-repo checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-lime-shrew.sh
        container: qc.sty_wimpy-cardinal-termite
      github.com/kit-data-manager/base-repo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-mustard-wombat.sh
        container: qc.sty_geeky-apricot-bobcat
      github.com/kit-data-manager/base-repo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-silver-toucan.sh
        container: qc.sty_sunny-lilac-moth
  QC.Ver:
    repos:
      github.com/kit-data-manager/base-repo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-orchid-ibis.sh
        container: qc.ver_cozy-seashell-turtle
timeout: 5400
